mlx4: work around compilation error with some versions of GCC
include/infiniband/verbs.h:475: error: ISO C doesn't support unnamed
 structs/unions

This error is caused by the recent addition of RSS support to verbs.h,
which uses a non-standard union definition (as in the kernel
implementation).

Acked-by: Damien Millescamps <damien.millescamps@6wind.com>
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>